import {
  Activity,
  AlarmClock,
  Anchor,
  ArrowDownWideNarrow,
  ArrowRight,
  ArrowUpDown,
  Atom,
  AtSign,
  Award,
  Backpack,
  BadgeCheck,
  BellRing,
  Binary,
  Bird,
  Blocks,
  BookMarked,
  BookOpen,
  Bot,
  Box,
  Boxes,
  Braces,
  BrainCircuit,
  BrickWall,
  Briefcase,
  Bug,
  Building2,
  CalendarCheck,
  CalendarDays,
  Castle,
  Cat,
  Check,
  CircleCheck,
  CircleDashed,
  CircleSlash,
  ClipboardCheck,
  Cloud,
  CodeXml,
  Coffee,
  Compass,
  Component,
  Construction,
  Container,
  Cpu,
  Crosshair,
  Crown,
  Database,
  DatabaseZap,
  Divide,
  Drama,
  Eye,
  FileArchive,
  FileBadge,
  FileCheck2,
  FileCode,
  Flag,
  FlagTriangleRight,
  Flame,
  FlaskConical,
  Footprints,
  Gauge,
  Gem,
  Gift,
  GitBranch,
  GitFork,
  Glasses,
  Globe,
  GraduationCap,
  Grid3x3,
  Hammer,
  Hash,
  Headphones,
  Hourglass,
  Infinity as InfinityIcon,
  IterationCw,
  Keyboard,
  KeyRound,
  Landmark,
  Layers,
  Library,
  LibraryBig,
  Lightbulb,
  List,
  ListEnd,
  ListOrdered,
  ListTree,
  Lock,
  LockKeyhole,
  type LucideIcon,
  Map as MapIcon,
  Medal,
  Moon,
  Mountain,
  Network,
  NotebookPen,
  Orbit,
  Package,
  Pencil,
  Play,
  Plug,
  Presentation,
  Puzzle,
  Pyramid,
  Quote,
  Recycle,
  RefreshCw,
  Regex,
  Repeat,
  Rocket,
  RotateCcw,
  Router,
  Ruler,
  Satellite,
  ScanEye,
  ScanSearch,
  School,
  Scroll,
  ScrollText,
  Search,
  Server,
  ServerCog,
  Shapes,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  ShipWheel,
  Sigma,
  Siren,
  Skull,
  Smile,
  Snowflake,
  Sparkles,
  Split,
  Sprout,
  SquareFunction,
  Stamp,
  Star,
  Sunrise,
  Swords,
  Table,
  Target,
  Telescope,
  Terminal,
  Timer,
  TrendingUp,
  Trophy,
  Type,
  Unlink,
  WandSparkles,
  Waves,
  Webhook,
  Workflow,
  Wrench,
  X,
  Zap,
} from "lucide-react";
import { cn } from "@/lib/cn";
import type { IconName } from "@/lib/icons";

const ICONS: Record<IconName, LucideIcon> = {
  binary: Binary,
  bug: Bug,
  cpu: Cpu,
  "git-branch": GitBranch,
  hammer: Hammer,
  infinity: InfinityIcon,
  library: Library,
  network: Network,
  recycle: Recycle,
  server: Server,
  "wand-sparkles": WandSparkles,
  "arrow-right": ArrowRight,
  award: Award,
  "book-open": BookOpen,
  bot: Bot,
  box: Box,
  "brain-circuit": BrainCircuit,
  "brick-wall": BrickWall,
  briefcase: Briefcase,
  "calendar-days": CalendarDays,
  cat: Cat,
  check: Check,
  "circle-check": CircleCheck,
  coffee: Coffee,
  compass: Compass,
  crosshair: Crosshair,
  crown: Crown,
  divide: Divide,
  flame: Flame,
  flask: FlaskConical,
  gem: Gem,
  gift: Gift,
  glasses: Glasses,
  globe: Globe,
  "graduation-cap": GraduationCap,
  grid: Grid3x3,
  headphones: Headphones,
  keyboard: Keyboard,
  landmark: Landmark,
  layers: Layers,
  lightbulb: Lightbulb,
  lock: Lock,
  map: MapIcon,
  medal: Medal,
  moon: Moon,
  package: Package,
  play: Play,
  puzzle: Puzzle,
  repeat: Repeat,
  rocket: Rocket,
  "rotate-ccw": RotateCcw,
  satellite: Satellite,
  "shield-check": ShieldCheck,
  smile: Smile,
  snowflake: Snowflake,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  sunrise: Sunrise,
  swords: Swords,
  target: Target,
  timer: Timer,
  trophy: Trophy,
  wrench: Wrench,
  x: X,
  zap: Zap,
  terminal: Terminal,
  type: Type,
  split: Split,
  anchor: Anchor,
  braces: Braces,
  "square-function": SquareFunction,
  "scan-search": ScanSearch,
  quote: Quote,
  "list-ordered": ListOrdered,
  hash: Hash,
  "refresh-cw": RefreshCw,
  "arrow-down-wide-narrow": ArrowDownWideNarrow,
  search: Search,
  shapes: Shapes,
  construction: Construction,
  drama: Drama,
  component: Component,
  plug: Plug,
  list: List,
  "circle-slash": CircleSlash,
  "shield-alert": ShieldAlert,
  "scroll-text": ScrollText,
  "list-tree": ListTree,
  table: Table,
  boxes: Boxes,
  "list-end": ListEnd,
  "code-xml": CodeXml,
  "iteration-cw": IterationCw,
  "arrow-up-down": ArrowUpDown,
  "file-code": FileCode,
  waves: Waves,
  workflow: Workflow,
  "circle-dashed": CircleDashed,
  regex: Regex,
  sigma: Sigma,
  "at-sign": AtSign,
  "scan-eye": ScanEye,
  "file-archive": FileArchive,
  "lock-keyhole": LockKeyhole,
  flag: Flag,
  unlink: Unlink,
  container: Container,
  router: Router,
  database: Database,
  "database-zap": DatabaseZap,
  webhook: Webhook,
  blocks: Blocks,
  pyramid: Pyramid,
  "server-cog": ServerCog,
  cloud: Cloud,
  ship: Ship,
  "ship-wheel": ShipWheel,
  gauge: Gauge,
  mountain: Mountain,
  telescope: Telescope,
  atom: Atom,
  shield: Shield,
  siren: Siren,
  activity: Activity,
  "git-fork": GitFork,
  castle: Castle,
  eye: Eye,
  bird: Bird,
  orbit: Orbit,
  scroll: Scroll,
  skull: Skull,
  school: School,
  backpack: Backpack,
  "notebook-pen": NotebookPen,
  pencil: Pencil,
  ruler: Ruler,
  "clipboard-check": ClipboardCheck,
  "book-marked": BookMarked,
  presentation: Presentation,
  "bell-ring": BellRing,
  stamp: Stamp,
  "badge-check": BadgeCheck,
  "building-2": Building2,
  "library-big": LibraryBig,
  "key-round": KeyRound,
  "flag-triangle-right": FlagTriangleRight,
  hourglass: Hourglass,
  "alarm-clock": AlarmClock,
  "calendar-check": CalendarCheck,
  "file-check-2": FileCheck2,
  "file-badge": FileBadge,
  footprints: Footprints,
  "trending-up": TrendingUp,
};

/**
 * SVG-иконка по имени из lib/icons.ts. Декоративная по умолчанию: смысл передаёт соседний текст.
 * Цвет — currentColor, размер — через className (size-4 и т.п.).
 */
export function Icon({
  name,
  className,
  strokeWidth = 2,
  label,
}: {
  name: IconName;
  className?: string;
  strokeWidth?: number;
  /** Подпись для скринридера, если иконка без текста рядом */
  label?: string;
}) {
  const Svg = ICONS[name];
  return (
    <Svg
      className={cn("size-4 shrink-0", className)}
      strokeWidth={strokeWidth}
      aria-hidden={label ? undefined : true}
      aria-label={label}
      role={label ? "img" : undefined}
      focusable="false"
    />
  );
}
