/**
 * Имена SVG-иконок сайта. Данные (ранги, достижения, квесты, quest.yaml) хранят имя, а рисует его
 * components/ui/icon.tsx. Список закрытый: схема контента проверяет, что в quest.yaml нет опечаток.
 */
export const ICON_NAMES = [
  "arrow-right",
  "award",
  "book-open",
  "bot",
  "box",
  "brain-circuit",
  "brick-wall",
  "briefcase",
  "calendar-days",
  "cat",
  "check",
  "circle-check",
  "coffee",
  "compass",
  "crosshair",
  "crown",
  "divide",
  "flame",
  "flask",
  "gem",
  "gift",
  "glasses",
  "globe",
  "graduation-cap",
  "grid",
  "headphones",
  "keyboard",
  "landmark",
  "layers",
  "lightbulb",
  "lock",
  "map",
  "medal",
  "moon",
  "package",
  "play",
  "puzzle",
  "repeat",
  "rocket",
  "rotate-ccw",
  "satellite",
  "shield-check",
  "smile",
  "snowflake",
  "sparkles",
  "sprout",
  "star",
  "sunrise",
  "swords",
  "target",
  "timer",
  "trophy",
  "wrench",
  "x",
  "zap",
] as const;

export type IconName = (typeof ICON_NAMES)[number];
